
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: my_test
    password: my_test
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl

server:
  port: 8888
  address: 192.168.179.77

